--ACTUALIZAR
/*
ALTER TABLE SEC_ROLE ADD REMOVED BIT NOT NULL;
ALTER TABLE SEC_ROLE ADD DESCRIPTION NVARCHAR(200) NULL;


ALTER TABLE SEC_SESSION ADD LOGOUT_DATE DATETIME NULL;


ALTER TABLE SEC_USER ADD REMOVED BIT NOT NULL;
ALTER TABLE SEC_USER ADD REMOVE_DATE DATETIME NULL;
ALTER TABLE SEC_USER ADD CREATE_DATE DATETIME NOT NULL;
ALTER TABLE SEC_USER ADD UPDATE_DATE DATETIME NULL;
ALTER TABLE SEC_USER ADD REMOVE_USER_ID INT  NULL;
ALTER TABLE SEC_USER ADD CREATE_USER_ID INT NULL;
ALTER TABLE SEC_USER ADD UPDATE_USER_ID INT NULL;

CREATE TABLE SEC_FORM(
ID INT IDENTITY NOT NULL PRIMARY KEY,
NAME NVARCHAR(100),
URL NVARCHAR(100)
)

CREATE TABLE SEC_FORMS_ROLE(
ID INT IDENTITY PRIMARY KEY NOT NULL,
ROLE_ID INT NOT NULL,
FORM_ID INT NOT NULL,
FOREIGN KEY(ROLE_ID) REFERENCES SEC_ROLE,
FOREIGN KEY (FORM_ID) REFERENCES SEC_FORM
)

------------------------------------------------SCRIPT ACTUALIZADO---------------------------------------

DROP TABLE PARAM_PAYMENTS;
DROP TABLE PARAM_REQUEST;
DROP TABLE PARAM_REQUEST_STATUS;
DROP TABLE PARAM_PROPERTY;
DROP TABLE PARAM_BLOCK:
DROP TABLE PARAM_PROJECT;
DROP TABLE PARAM_FINANCIAL;
DROP TABLE PARAM_CUSTOMER;
DROP TABLE PARAM_CITY;
DROP TABLE PARAM_COUNTRY;

CREATE TABLE PARAM_COUNTRY(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE NVARCHAR(40) NOT NULL,
NAME NVARCHAR(50) NOT NULL
)

CREATE TABLE PARAM_CITY(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE NVARCHAR(40) NOT NULL,
NAME NVARCHAR(50) NOT NULL,
COUNTRYID INT NOT NULL,
FOREIGN KEY (COUNTRYID) REFERENCES PARAM_COUNTRY,
)

CREATE TABLE PARAM_CUSTOMER(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
DOCUMENT NVARCHAR(40) NOT NULL,
NAME NVARCHAR(50) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
DATEBIRTH DATETIME NOT NULL,
PICTURE NVARCHAR(MAX),
CELLPHONE NVARCHAR(30) NOT NULL,
EMAIL NVARCHAR(100) NOT NULL,
ADDRESS NVARCHAR(50) NOT NULL,
CITYID INT NOT NULL,
FOREIGN KEY (CITYID) REFERENCES PARAM_CITY,
)

CREATE TABLE PARAM_FINANCIAL(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CUSTOMERID INT NOT NULL,
NAMEJOB NVARCHAR(50) NOT NULL,
PHONEJOB NVARCHAR(30) NOT NULL,
TOTALINCOME INT NOT NULL,
TIMECURRENTJOB DATETIME NOT NULL,
NAMEFAMILYREF NVARCHAR(50) NOT NULL,
CELLPHONEFAMILYREF NVARCHAR(30) NOT NULL,
NAMEPERSONALREF NVARCHAR(50) NOT NULL,
CELLPHONEPERSONALREF NVARCHAR(30) NOT NULL,
FOREIGN KEY (CUSTOMERID) REFERENCES PARAM_CUSTOMER,
)

CREATE TABLE PARAM_PROJECT(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE NVARCHAR(40) NOT NULL,
NAME NVARCHAR(50) NOT NULL,
DESCRIPTION NVARCHAR(MAX) NOT NULL,
PICTURE NVARCHAR(MAX),
CITYID INT NOT NULL,
FOREIGN KEY (CITYID) REFERENCES PARAM_CITY,
)

CREATE TABLE PARAM_BLOCK(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE NVARCHAR(40) NOT NULL,
NAME NVARCHAR(50) NOT NULL,
DESCRIPTION NVARCHAR(MAX) NOT NULL,
PROJECTID INT NOT NULL,
FOREIGN KEY (PROJECTID) REFERENCES PARAM_PROJECT,
)

CREATE TABLE PARAM_PROPERTY(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE NVARCHAR(40) NOT NULL,
NAME NVARCHAR(50) NOT NULL,
VALOR INT NOT NULL,
BLOCKID INT NOT NULL,
FOREIGN KEY (BLOCKID) REFERENCES PARAM_BLOCK
)

CREATE TABLE PARAM_REQUEST_STATUS(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NAME NVARCHAR(50) NOT NULL,
DESCRIPTION NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE PARAM_REQUEST(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
DELIVERYDATE DATETIME NOT NULL,
APPROVEDDATE DATETIME NOT NULL,
ECONOMICOFFER INT NOT NULL,
CONSIGNMENT INT NOT NULL,
CUSTOMERID INT NOT NULL,
PROPERTYID INT NOT NULL,
REQUEST_STATUSID INT NOT NULL,
FOREIGN KEY (CUSTOMERID) REFERENCES PARAM_CUSTOMER,
FOREIGN KEY (PROPERTYID) REFERENCES PARAM_PROPERTY,
FOREIGN KEY (REQUEST_STATUSID) REFERENCES PARAM_REQUEST_STATUS
)

CREATE TABLE PARAM_PAYMENTS(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NAME NVARCHAR(50) NOT NULL,
DESCRIPTION NVARCHAR(MAX) NOT NULL,
DATE DATETIME NOT NULL,
REQUESTID INT NOT NULL
FOREIGN KEY (REQUESTID) REFERENCES PARAM_REQUEST
)



----------------------------------------------------- DATOS PARA AGREGAR A LAS TABLAS -----------------------------------

INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('6372','Colombia')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('5267','Estados Unidos')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('0728','Grecia')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('1563','España')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('6389','Canadá')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('2674','China')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('1702','Corea del Sur')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('2269','Dinamarca')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('5490','Australia')
INSERT INTO ConstructoraDB.dbo.PARAM_COUNTRY VALUES ('0265','México')
----------------------------------------------------
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('4278','Pekin','6')
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('9056','Darwin','9')
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('7396','Madrid','4')
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('0213','Manizales','1')
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('1578','Toronto','5')
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('8920','Atenas','3')
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('9320','Pereira','1')
INSERT INTO ConstructoraDB.dbo.PARAM_CITY VALUES ('4563','California','2')
----------------------------------------------------
INSERT INTO ConstructoraDB.dbo.PARAM_PROJECT VALUES ('5367','xxxx','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','N/A','1')
INSERT INTO ConstructoraDB.dbo.PARAM_PROJECT VALUES ('0781','yyyy','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','N/A','5')
INSERT INTO ConstructoraDB.dbo.PARAM_PROJECT VALUES ('4682','zzzz','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','N/A','2')
INSERT INTO ConstructoraDB.dbo.PARAM_PROJECT VALUES ('6380','aaaa','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','N/A','6')
INSERT INTO ConstructoraDB.dbo.PARAM_PROJECT VALUES ('7652','bbbb','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','N/A','3')
----------------------------------------------------
INSERT INTO ConstructoraDB.dbo.PARAM_BLOCK VALUES ('7832','A','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','2')
INSERT INTO ConstructoraDB.dbo.PARAM_BLOCK VALUES ('9847','B','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','5')
INSERT INTO ConstructoraDB.dbo.PARAM_BLOCK VALUES ('2367','C','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','1')
INSERT INTO ConstructoraDB.dbo.PARAM_BLOCK VALUES ('8734','D','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','4')
INSERT INTO ConstructoraDB.dbo.PARAM_BLOCK VALUES ('2023','E','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','3')


*/