--ACTUALIZAR
/*
ALTER TABLE SEC_ROLE ADD REMOVED BIT NOT NULL;
ALTER TABLE SEC_ROLE ADD DESCRIPTION NVARCHAR(200) NULL;


ALTER TABLE SEC_SESSION ADD LOGOUT_DATE DATETIME NULL;


ALTER TABLE SEC_USER ADD REMOVED BIT NOT NULL;
ALTER TABLE SEC_USER ADD REMOVE_DATE DATETIME NULL;
ALTER TABLE SEC_USER ADD CREATE_DATE DATETIME NOT NULL;
ALTER TABLE SEC_USER ADD UPDATE_DATE DATETIME NULL;
ALTER TABLE SEC_USER ADD REMOVE_USER_ID INT  NULL;
ALTER TABLE SEC_USER ADD CREATE_USER_ID INT NULL;
ALTER TABLE SEC_USER ADD UPDATE_USER_ID INT NULL;*/