//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_BLOCK
    {
        public PARAM_BLOCK()
        {
            this.PARAM_PROPERTY = new HashSet<PARAM_PROPERTY>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int PROJECTID { get; set; }
    
        public virtual PARAM_PROJECT PARAM_PROJECT { get; set; }
        public virtual ICollection<PARAM_PROPERTY> PARAM_PROPERTY { get; set; }
    }
}
