//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_PROPERTY
    {
        public PARAM_PROPERTY()
        {
            this.PARAM_REQUEST = new HashSet<PARAM_REQUEST>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public int BLOCKID { get; set; }
        public int VALUE { get; set; }
    
        public virtual PARAM_BLOCK PARAM_BLOCK { get; set; }
        public virtual ICollection<PARAM_REQUEST> PARAM_REQUEST { get; set; }
    }
}
