//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_CUSTOMER
    {
        public PARAM_CUSTOMER()
        {
            this.PARAM_REQUEST = new HashSet<PARAM_REQUEST>();
        }
    
        public int ID { get; set; }
        public string DOCUMENT { get; set; }
        public string NAME { get; set; }
        public string LASTNAMEN { get; set; }
        public System.DateTime DATEBIRTH { get; set; }
        public string PICTURE { get; set; }
        public string CELLPHONE { get; set; }
        public string EMAIL { get; set; }
        public string ADRESS { get; set; }
        public int CITYID { get; set; }
        public int FINANCIALID { get; set; }
    
        public virtual PARAM_CITY PARAM_CITY { get; set; }
        public virtual PARAM_FINANCIAL PARAM_FINANCIAL { get; set; }
        public virtual ICollection<PARAM_REQUEST> PARAM_REQUEST { get; set; }
    }
}
