//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_PROJECT
    {
        public PARAM_PROJECT()
        {
            this.PARAM_BLOCK = new HashSet<PARAM_BLOCK>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string PROJ_DESCRIPTION { get; set; }
        public string PICTURE { get; set; }
        public int CITYID { get; set; }
    
        public virtual ICollection<PARAM_BLOCK> PARAM_BLOCK { get; set; }
        public virtual PARAM_CITY PARAM_CITY { get; set; }
    }
}
