//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_REQUEST
    {
        public PARAM_REQUEST()
        {
            this.PARAM_PAYMENTS = new HashSet<PARAM_PAYMENTS>();
        }
    
        public int ID { get; set; }
        public System.DateTime DELIVERYDATE { get; set; }
        public int ECONOMICOFFER { get; set; }
        public int CUSTOMERID { get; set; }
        public int PROPERTYID { get; set; }
        public int REQUEST_STATUSID { get; set; }
    
        public virtual PARAM_CUSTOMER PARAM_CUSTOMER { get; set; }
        public virtual ICollection<PARAM_PAYMENTS> PARAM_PAYMENTS { get; set; }
        public virtual PARAM_PROPERTY PARAM_PROPERTY { get; set; }
        public virtual PARAM_REQUEST_STATUS PARAM_REQUEST_STATUS { get; set; }
    }
}
