//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_FINANCIAL
    {
        public PARAM_FINANCIAL()
        {
            this.PARAM_CUSTOMER = new HashSet<PARAM_CUSTOMER>();
        }
    
        public int ID { get; set; }
        public string NAME_JOB { get; set; }
        public string PHONE_JOB { get; set; }
        public int TOTAL_IN_COME { get; set; }
        public System.DateTime TIME_CURRENT_WORK { get; set; }
        public string NAME_FAMILY_REF { get; set; }
        public string CELLPHONE_FAMILY_REF { get; set; }
        public string NAME_PERSONAL_REF { get; set; }
        public string CELLPHONE_PERSONAL_REF { get; set; }
    
        public virtual ICollection<PARAM_CUSTOMER> PARAM_CUSTOMER { get; set; }
    }
}
